export type PhoneCountry = {
  code: string;
  dial: string;
  label: string;
};

/** Full ISO-style country list with international dialing codes. */
export const PHONE_COUNTRIES: PhoneCountry[] = [
  { code: "AF", dial: "+93", label: "Afghanistan" },
  { code: "AL", dial: "+355", label: "Albania" },
  { code: "DZ", dial: "+213", label: "Algeria" },
  { code: "AS", dial: "+1", label: "American Samoa" },
  { code: "AD", dial: "+376", label: "Andorra" },
  { code: "AO", dial: "+244", label: "Angola" },
  { code: "AI", dial: "+1264", label: "Anguilla" },
  { code: "AG", dial: "+1268", label: "Antigua and Barbuda" },
  { code: "AR", dial: "+54", label: "Argentina" },
  { code: "AM", dial: "+374", label: "Armenia" },
  { code: "AW", dial: "+297", label: "Aruba" },
  { code: "AU", dial: "+61", label: "Australia" },
  { code: "AT", dial: "+43", label: "Austria" },
  { code: "AZ", dial: "+994", label: "Azerbaijan" },
  { code: "BS", dial: "+1242", label: "Bahamas" },
  { code: "BH", dial: "+973", label: "Bahrain" },
  { code: "BD", dial: "+880", label: "Bangladesh" },
  { code: "BB", dial: "+1246", label: "Barbados" },
  { code: "BY", dial: "+375", label: "Belarus" },
  { code: "BE", dial: "+32", label: "Belgium" },
  { code: "BZ", dial: "+501", label: "Belize" },
  { code: "BJ", dial: "+229", label: "Benin" },
  { code: "BM", dial: "+1441", label: "Bermuda" },
  { code: "BT", dial: "+975", label: "Bhutan" },
  { code: "BO", dial: "+591", label: "Bolivia" },
  { code: "BA", dial: "+387", label: "Bosnia and Herzegovina" },
  { code: "BW", dial: "+267", label: "Botswana" },
  { code: "BR", dial: "+55", label: "Brazil" },
  { code: "IO", dial: "+246", label: "British Indian Ocean Territory" },
  { code: "VG", dial: "+1284", label: "British Virgin Islands" },
  { code: "BN", dial: "+673", label: "Brunei" },
  { code: "BG", dial: "+359", label: "Bulgaria" },
  { code: "BF", dial: "+226", label: "Burkina Faso" },
  { code: "BI", dial: "+257", label: "Burundi" },
  { code: "KH", dial: "+855", label: "Cambodia" },
  { code: "CM", dial: "+237", label: "Cameroon" },
  { code: "CA", dial: "+1", label: "Canada" },
  { code: "CV", dial: "+238", label: "Cape Verde" },
  { code: "KY", dial: "+1345", label: "Cayman Islands" },
  { code: "CF", dial: "+236", label: "Central African Republic" },
  { code: "TD", dial: "+235", label: "Chad" },
  { code: "CL", dial: "+56", label: "Chile" },
  { code: "CN", dial: "+86", label: "China" },
  { code: "CX", dial: "+61", label: "Christmas Island" },
  { code: "CC", dial: "+61", label: "Cocos Islands" },
  { code: "CO", dial: "+57", label: "Colombia" },
  { code: "KM", dial: "+269", label: "Comoros" },
  { code: "CK", dial: "+682", label: "Cook Islands" },
  { code: "CR", dial: "+506", label: "Costa Rica" },
  { code: "HR", dial: "+385", label: "Croatia" },
  { code: "CU", dial: "+53", label: "Cuba" },
  { code: "CW", dial: "+599", label: "Curaçao" },
  { code: "CY", dial: "+357", label: "Cyprus" },
  { code: "CZ", dial: "+420", label: "Czech Republic" },
  { code: "CD", dial: "+243", label: "DR Congo" },
  { code: "DK", dial: "+45", label: "Denmark" },
  { code: "DJ", dial: "+253", label: "Djibouti" },
  { code: "DM", dial: "+1767", label: "Dominica" },
  { code: "DO", dial: "+1809", label: "Dominican Republic" },
  { code: "EC", dial: "+593", label: "Ecuador" },
  { code: "EG", dial: "+20", label: "Egypt" },
  { code: "SV", dial: "+503", label: "El Salvador" },
  { code: "GQ", dial: "+240", label: "Equatorial Guinea" },
  { code: "ER", dial: "+291", label: "Eritrea" },
  { code: "EE", dial: "+372", label: "Estonia" },
  { code: "SZ", dial: "+268", label: "Eswatini" },
  { code: "ET", dial: "+251", label: "Ethiopia" },
  { code: "FK", dial: "+500", label: "Falkland Islands" },
  { code: "FO", dial: "+298", label: "Faroe Islands" },
  { code: "FJ", dial: "+679", label: "Fiji" },
  { code: "FI", dial: "+358", label: "Finland" },
  { code: "FR", dial: "+33", label: "France" },
  { code: "GF", dial: "+594", label: "French Guiana" },
  { code: "PF", dial: "+689", label: "French Polynesia" },
  { code: "GA", dial: "+241", label: "Gabon" },
  { code: "GM", dial: "+220", label: "Gambia" },
  { code: "GE", dial: "+995", label: "Georgia" },
  { code: "DE", dial: "+49", label: "Germany" },
  { code: "GH", dial: "+233", label: "Ghana" },
  { code: "GI", dial: "+350", label: "Gibraltar" },
  { code: "GR", dial: "+30", label: "Greece" },
  { code: "GL", dial: "+299", label: "Greenland" },
  { code: "GD", dial: "+1473", label: "Grenada" },
  { code: "GP", dial: "+590", label: "Guadeloupe" },
  { code: "GU", dial: "+1", label: "Guam" },
  { code: "GT", dial: "+502", label: "Guatemala" },
  { code: "GG", dial: "+44", label: "Guernsey" },
  { code: "GN", dial: "+224", label: "Guinea" },
  { code: "GW", dial: "+245", label: "Guinea-Bissau" },
  { code: "GY", dial: "+592", label: "Guyana" },
  { code: "HT", dial: "+509", label: "Haiti" },
  { code: "HN", dial: "+504", label: "Honduras" },
  { code: "HK", dial: "+852", label: "Hong Kong" },
  { code: "HU", dial: "+36", label: "Hungary" },
  { code: "IS", dial: "+354", label: "Iceland" },
  { code: "IN", dial: "+91", label: "India" },
  { code: "ID", dial: "+62", label: "Indonesia" },
  { code: "IR", dial: "+98", label: "Iran" },
  { code: "IQ", dial: "+964", label: "Iraq" },
  { code: "IE", dial: "+353", label: "Ireland" },
  { code: "IM", dial: "+44", label: "Isle of Man" },
  { code: "IL", dial: "+972", label: "Israel" },
  { code: "IT", dial: "+39", label: "Italy" },
  { code: "CI", dial: "+225", label: "Ivory Coast" },
  { code: "JM", dial: "+1876", label: "Jamaica" },
  { code: "JP", dial: "+81", label: "Japan" },
  { code: "JE", dial: "+44", label: "Jersey" },
  { code: "JO", dial: "+962", label: "Jordan" },
  { code: "KZ", dial: "+7", label: "Kazakhstan" },
  { code: "KE", dial: "+254", label: "Kenya" },
  { code: "KI", dial: "+686", label: "Kiribati" },
  { code: "XK", dial: "+383", label: "Kosovo" },
  { code: "KW", dial: "+965", label: "Kuwait" },
  { code: "KG", dial: "+996", label: "Kyrgyzstan" },
  { code: "LA", dial: "+856", label: "Laos" },
  { code: "LV", dial: "+371", label: "Latvia" },
  { code: "LB", dial: "+961", label: "Lebanon" },
  { code: "LS", dial: "+266", label: "Lesotho" },
  { code: "LR", dial: "+231", label: "Liberia" },
  { code: "LY", dial: "+218", label: "Libya" },
  { code: "LI", dial: "+423", label: "Liechtenstein" },
  { code: "LT", dial: "+370", label: "Lithuania" },
  { code: "LU", dial: "+352", label: "Luxembourg" },
  { code: "MO", dial: "+853", label: "Macau" },
  { code: "MG", dial: "+261", label: "Madagascar" },
  { code: "MW", dial: "+265", label: "Malawi" },
  { code: "MY", dial: "+60", label: "Malaysia" },
  { code: "MV", dial: "+960", label: "Maldives" },
  { code: "ML", dial: "+223", label: "Mali" },
  { code: "MT", dial: "+356", label: "Malta" },
  { code: "MH", dial: "+692", label: "Marshall Islands" },
  { code: "MQ", dial: "+596", label: "Martinique" },
  { code: "MR", dial: "+222", label: "Mauritania" },
  { code: "MU", dial: "+230", label: "Mauritius" },
  { code: "YT", dial: "+262", label: "Mayotte" },
  { code: "MX", dial: "+52", label: "Mexico" },
  { code: "FM", dial: "+691", label: "Micronesia" },
  { code: "MD", dial: "+373", label: "Moldova" },
  { code: "MC", dial: "+377", label: "Monaco" },
  { code: "MN", dial: "+976", label: "Mongolia" },
  { code: "ME", dial: "+382", label: "Montenegro" },
  { code: "MS", dial: "+1664", label: "Montserrat" },
  { code: "MA", dial: "+212", label: "Morocco" },
  { code: "MZ", dial: "+258", label: "Mozambique" },
  { code: "MM", dial: "+95", label: "Myanmar" },
  { code: "NA", dial: "+264", label: "Namibia" },
  { code: "NR", dial: "+674", label: "Nauru" },
  { code: "NP", dial: "+977", label: "Nepal" },
  { code: "NL", dial: "+31", label: "Netherlands" },
  { code: "NC", dial: "+687", label: "New Caledonia" },
  { code: "NZ", dial: "+64", label: "New Zealand" },
  { code: "NI", dial: "+505", label: "Nicaragua" },
  { code: "NE", dial: "+227", label: "Niger" },
  { code: "NG", dial: "+234", label: "Nigeria" },
  { code: "NU", dial: "+683", label: "Niue" },
  { code: "NF", dial: "+672", label: "Norfolk Island" },
  { code: "KP", dial: "+850", label: "North Korea" },
  { code: "MK", dial: "+389", label: "North Macedonia" },
  { code: "MP", dial: "+1", label: "Northern Mariana Islands" },
  { code: "NO", dial: "+47", label: "Norway" },
  { code: "OM", dial: "+968", label: "Oman" },
  { code: "PK", dial: "+92", label: "Pakistan" },
  { code: "PW", dial: "+680", label: "Palau" },
  { code: "PS", dial: "+970", label: "Palestine" },
  { code: "PA", dial: "+507", label: "Panama" },
  { code: "PG", dial: "+675", label: "Papua New Guinea" },
  { code: "PY", dial: "+595", label: "Paraguay" },
  { code: "PE", dial: "+51", label: "Peru" },
  { code: "PH", dial: "+63", label: "Philippines" },
  { code: "PL", dial: "+48", label: "Poland" },
  { code: "PT", dial: "+351", label: "Portugal" },
  { code: "PR", dial: "+1", label: "Puerto Rico" },
  { code: "QA", dial: "+974", label: "Qatar" },
  { code: "CG", dial: "+242", label: "Republic of the Congo" },
  { code: "RE", dial: "+262", label: "Réunion" },
  { code: "RO", dial: "+40", label: "Romania" },
  { code: "RU", dial: "+7", label: "Russia" },
  { code: "RW", dial: "+250", label: "Rwanda" },
  { code: "BL", dial: "+590", label: "Saint Barthélemy" },
  { code: "SH", dial: "+290", label: "Saint Helena" },
  { code: "KN", dial: "+1869", label: "Saint Kitts and Nevis" },
  { code: "LC", dial: "+1758", label: "Saint Lucia" },
  { code: "MF", dial: "+590", label: "Saint Martin" },
  { code: "PM", dial: "+508", label: "Saint Pierre and Miquelon" },
  { code: "VC", dial: "+1784", label: "Saint Vincent and the Grenadines" },
  { code: "WS", dial: "+685", label: "Samoa" },
  { code: "SM", dial: "+378", label: "San Marino" },
  { code: "ST", dial: "+239", label: "São Tomé and Príncipe" },
  { code: "SA", dial: "+966", label: "Saudi Arabia" },
  { code: "SN", dial: "+221", label: "Senegal" },
  { code: "RS", dial: "+381", label: "Serbia" },
  { code: "SC", dial: "+248", label: "Seychelles" },
  { code: "SL", dial: "+232", label: "Sierra Leone" },
  { code: "SG", dial: "+65", label: "Singapore" },
  { code: "SX", dial: "+1721", label: "Sint Maarten" },
  { code: "SK", dial: "+421", label: "Slovakia" },
  { code: "SI", dial: "+386", label: "Slovenia" },
  { code: "SB", dial: "+677", label: "Solomon Islands" },
  { code: "SO", dial: "+252", label: "Somalia" },
  { code: "ZA", dial: "+27", label: "South Africa" },
  { code: "KR", dial: "+82", label: "South Korea" },
  { code: "SS", dial: "+211", label: "South Sudan" },
  { code: "ES", dial: "+34", label: "Spain" },
  { code: "LK", dial: "+94", label: "Sri Lanka" },
  { code: "SD", dial: "+249", label: "Sudan" },
  { code: "SR", dial: "+597", label: "Suriname" },
  { code: "SJ", dial: "+47", label: "Svalbard and Jan Mayen" },
  { code: "SE", dial: "+46", label: "Sweden" },
  { code: "CH", dial: "+41", label: "Switzerland" },
  { code: "SY", dial: "+963", label: "Syria" },
  { code: "TW", dial: "+886", label: "Taiwan" },
  { code: "TJ", dial: "+992", label: "Tajikistan" },
  { code: "TZ", dial: "+255", label: "Tanzania" },
  { code: "TH", dial: "+66", label: "Thailand" },
  { code: "TL", dial: "+670", label: "Timor-Leste" },
  { code: "TG", dial: "+228", label: "Togo" },
  { code: "TK", dial: "+690", label: "Tokelau" },
  { code: "TO", dial: "+676", label: "Tonga" },
  { code: "TT", dial: "+1868", label: "Trinidad and Tobago" },
  { code: "TN", dial: "+216", label: "Tunisia" },
  { code: "TR", dial: "+90", label: "Turkey" },
  { code: "TM", dial: "+993", label: "Turkmenistan" },
  { code: "TC", dial: "+1649", label: "Turks and Caicos Islands" },
  { code: "TV", dial: "+688", label: "Tuvalu" },
  { code: "VI", dial: "+1", label: "U.S. Virgin Islands" },
  { code: "UG", dial: "+256", label: "Uganda" },
  { code: "UA", dial: "+380", label: "Ukraine" },
  { code: "AE", dial: "+971", label: "United Arab Emirates" },
  { code: "GB", dial: "+44", label: "United Kingdom" },
  { code: "US", dial: "+1", label: "United States" },
  { code: "UY", dial: "+598", label: "Uruguay" },
  { code: "UZ", dial: "+998", label: "Uzbekistan" },
  { code: "VU", dial: "+678", label: "Vanuatu" },
  { code: "VA", dial: "+39", label: "Vatican City" },
  { code: "VE", dial: "+58", label: "Venezuela" },
  { code: "VN", dial: "+84", label: "Vietnam" },
  { code: "WF", dial: "+681", label: "Wallis and Futuna" },
  { code: "EH", dial: "+212", label: "Western Sahara" },
  { code: "YE", dial: "+967", label: "Yemen" },
  { code: "ZM", dial: "+260", label: "Zambia" },
  { code: "ZW", dial: "+263", label: "Zimbabwe" },
];

export const DEFAULT_PHONE_COUNTRY = "JP";
export const DEFAULT_PHONE_DIAL = "+81";

export function getPhoneDial(code: string): string {
  return PHONE_COUNTRIES.find((c) => c.code === code)?.dial ?? DEFAULT_PHONE_DIAL;
}

/** Country names for destination/country selects (sorted A–Z). */
export const COUNTRY_NAMES = PHONE_COUNTRIES.map((c) => c.label).sort((a, b) =>
  a.localeCompare(b),
);
